url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title: Resident Geek
copyright: 2025 Resident Geek

ga_code: UA-3911154-1

author:
  name: Daniel Smith # the name of your site, e.g. ACME Corp.
  title: Software Engineer & Architect

social_links:
  Github: https://github.com/danielrsmith
  Instagram: https://instagram.com/danielrsmith
  LinkedIn: https://www.linkedin.com/in/danielrs

